### ISSUE TITLE
TypeError: this._log is not a function

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [Ents24/testcafe-browser-provider-fbsimctl#1]
Hi, thanks for the cool provider.

I've found that you call `this._log` method of the provider if `iOS version` is not set, but this function is not defined: https://github.com/Ents24/testcafe-browser-provider-fbsimctl/blob/master/src/index.js#L95

**Comment by dig412** [comment]
Aha, thanks for finding that - some left over debugging information.

I've fixed this now.
