### ISSUE TITLE
Listing browsers with "testcafe -b fbsimctl" doesn't work

### ISSUE THREAD

**Issue by dig412** [Ents24/testcafe-browser-provider-fbsimctl#2]
When running `testcafe -b fbsimctl` I expect to see a list of all available devices and platforms. Instead only `"fbsimctl"` is printed.

The `getBrowserList()` method is implemented, and returns an Array of strings, which is what the SauceLabs plugin does. (https://github.com/DevExpress/testcafe-browser-provider-saucelabs/blob/master/src/index.js#L359)

**Comment by AlexanderMoskovkin** [comment]
At first it necessary to set `isMultiBrowser` to true. And it seems it's required to do some other changes. I'm working on this right now, so I'm going to create a pull request with the fix soon
