### ISSUE TITLE
Second test run is not possible on simulated devices

### ISSUE THREAD

**Issue by HenningThiemann** [Ents24/testcafe-browser-provider-fbsimctl#7]
Hi, 
first of all thank you very much for your tool, it is very useful for our needs!

Currently, I am facing a bug, maybe you have experienced this as well. When I run my tests for the first time on a simulated device, everything is working fine. If I choose to run them again, Xcode opens the correct simulator, but it does not open up safari or the testcafe url. Obviously, the loop is not working as it should and I get a timeout after a while. But if I set up the device new, it is working again but only for the first time..

I am using Xcode 9.1 and iOS 11.1, but this error occurs in earlier iOS versions as well. 
Can you please give me a hint on how to solve this?

Thank you!

**Comment by HenningThiemann** [comment]
Ok, I have found a workaround. It is a bit dirty, but working. 

You can reset simulators by running `xcrun simctl erase all`. If you run this inside the openBrowser() function, all simulator content gets erased and the simulator acts as if it gets opened for the first time. Testcafe is then able to run the tests.

Are there any better ways to do this?

**Comment by darin-sai** [comment]
A year and a half later - seeing this issue. @HenningThiemann your workaround still applies. I dropped that command into `index.js` and the tests can be run multiple times.

```javascript
openBrowser: function openBrowser(id, pageUrl, browserName) {
    var _this = this;

    // Added this line:
    _child_process2.default.execSync('xcrun simctl erase all');

    return (0, _asyncToGenerator3.default)(_regenerator2.default.mark(function _callee() {
```

I'd love a less extreme workaround though, this adds a lot of setup time to the test execution.
